CREATE DATABASE UserStructs;
USE UserStructs;

DROP TABLE IF EXISTS Unsub00;
DROP TABLE IF EXISTS Unsub01;
DROP TABLE IF EXISTS Unsub02;
DROP TABLE IF EXISTS Unsub03;
DROP TABLE IF EXISTS Unsub04;

CREATE TABLE Unsub00 (
	id int NOT NULL AUTO_INCREMENT,
	uid int(255) NOT NULL,
	email varchar(255) DEFAULT NULL, PRIMARY KEY (id))
	DEFAULT CHARACTER SET utf8;
CREATE TABLE Unsub01 (
	id int NOT NULL AUTO_INCREMENT,
	uid int(255) NOT NULL,
	email varchar(255) DEFAULT NULL, PRIMARY KEY (id))
	DEFAULT CHARACTER SET utf8;
CREATE TABLE Unsub02 (
	id int NOT NULL AUTO_INCREMENT,
	uid int(255) NOT NULL,
	email varchar(255) DEFAULT NULL, PRIMARY KEY (id))
	DEFAULT CHARACTER SET utf8;
CREATE TABLE Unsub03 (
	id int NOT NULL AUTO_INCREMENT,
	uid int(255) NOT NULL,
	email varchar(255) DEFAULT NULL, PRIMARY KEY (id))
	DEFAULT CHARACTER SET utf8;
CREATE TABLE Unsub04 (
	id int NOT NULL AUTO_INCREMENT,
	uid int(255) NOT NULL,
	email varchar(255) DEFAULT NULL, PRIMARY KEY (id))
	DEFAULT CHARACTER SET utf8;
